#Derniere configuration d'execution VRPTW
#Wed Apr 01 11:55:44 CEST 2026
algo=sa
coolingRate=0.9995
enforceTimeWindows=false
estimateMinVehicles=true
initialStrategy=greedy
initialTemp=2500.0
instancePath=data/data101.vrp
iterations=30000
maxVehicles=2147483647
neighborhoodSize=40
penaltyWeight=1000.0
seed=42
tabuTenure=25
