#Derniere configuration d'execution VRPTW
#Fri Apr 24 10:18:11 CEST 2026
algo=tabu
coolingRate=0.9993
enforceTimeWindows=true
estimateMinVehicles=false
initialStrategy=random
initialTemp=1250.0
instancePath=data/data201.vrp
interNeighborhoodType=relocate
intraNeighborhoodType=
iterations=30000
maxVehicles=2147483647
neighborhoodFamily=inter
penaltyWeight=1000.0
seed=41
tabuTenure=40
