#Derniere configuration d'execution VRPTW
#Wed Apr 01 12:37:31 CEST 2026
algo=sa
coolingRate=0.9995
enforceTimeWindows=true
estimateMinVehicles=false
initialStrategy=greedy
initialTemp=2500.0
instancePath=data/data101.vrp
iterations=100000
maxVehicles=2147483647
neighborhoodSize=40
neighborhoodType=mixed
penaltyWeight=1000.0
saNeighborhoodType=mixed
seed=42
tabuTenure=25
